LIB = libOverlapDetection.a

skip_files =
LIBCCFILES = $(filter-out $(skip_files),$(wildcard *.cc))

include SoftRelTools/standard.mk
include SoftRelTools/refresh.mk
include SoftRelTools/arch_spec_root_minedm.mk
