# Makefile for BaBar package
#
# uses SoftRelTools/standard.mk
#
# This makefile just redirects the make to the needed
# subdirectories
#
#  revision history:
#  -----------------
# *0001 Sept 07 1997 P.Murat: add e5 (example of AC++ simulation module)
########################################################################
# file lists (standard names, local contents)
#
# include file products
INC = 

# library product
LIB = 

#library contents
LIBCFILES  =
LIBCCFILES = 

# subdirectories
SUBDIRS = isajet pythia vecbos Bgenerator wgrad 

# binary products
BINS = 
############################################################
include SoftRelTools/standard.mk
